### ISSUE TITLE
STS Parameters not passed on HTTP GET requests

### ISSUE THREAD

**Issue by newbeb** [Cox-Automotive/alks.js#33]
The accessKey, secretKey and sessionToken parameters are passed in the body of "non-GET" requests to the API. This effects running certain API calls using machine identity, ALKSify specifically.

STS credentials can (and should?) be passed via the ALKS-STS-Access-Key, ALKS-STS-Secret-Key, and ALKS-STS-Session-Token headers instead of in the body (which is a deprecated method).

Calling requests using the GET method currently return a 401 error with the message "Full authentication is required to access this resource".

**Comment by amagana3** [comment]
This has been fixed and released in the latest release: https://github.com/Cox-Automotive/alks.js/releases/tag/v1.10.1

Thanks for the PR @blncoxauto 👍
